<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>org.lixiyun</groupId>
    <artifactId>ai-mental-care</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <modules>
        <module>pojo</module>
        <module>common</module>
        <module>server</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>17</java.version>

        <revision>1.0.0</revision>
        <spring-boot.version>3.5.0</spring-boot.version>

        <!-- MySQL相关配置-->
        <mybatis.version>3.0.4</mybatis.version>
        <mysql.version>8.0.33</mysql.version>
        <druid.version>1.2.20</druid.version>
        <pagehelper.version>2.1.0</pagehelper.version>
        <mybatis-plus.version>3.5.15</mybatis-plus.version>

        <!-- Redis相关配置-->
        <redis.version>3.3.1</redis.version>
        <common.pool.version>2.12.1</common.pool.version>

        <lombok.version>1.18.36</lombok.version>
        <jjwt.version>0.12.6</jjwt.version>
        <hutool.version>5.8.35</hutool.version>
        <captcha.version>2.2.5</captcha.version>
        <httpclient.version>5.5</httpclient.version>
        <validator>8.0.1.Final</validator>

        <swagger.gateway>4.5.0</swagger.gateway>
        <aspectj.version>1.9.24</aspectj.version>
        <knife4j-openapi3-jakarta>4.5.0</knife4j-openapi3-jakarta>
        <springdoc.version>2.6.0</springdoc.version> <!-- 降级到与Spring Boot 3.3.6兼容的版本 2.8.14 -->
<!--        <springdoc-ui.version>2.6.0</springdoc-ui.version> &lt;!&ndash; 降级到与Spring Boot 3.3.6兼容的版本 3.0.0 &ndash;&gt;-->
        <springdoc-ui.version>2.8.9</springdoc-ui.version> <!-- 降级到与Spring Boot 3.3.6兼容的版本 3.0.0 -->

        <therapi-javadoc.version>0.15.0</therapi-javadoc.version>

        <poi.version>5.2.3</poi.version>
        <easyexcel.version>3.2.1</easyexcel.version>
        <velocity.version>2.3</velocity.version>

        <milvus.version>2.6.18</milvus.version>

        <dashscope-sdk-java>2.22.12</dashscope-sdk-java>

        <p6spy.version>3.9.1</p6spy.version>
        <okhttp.version>4.10.0</okhttp.version>
        <dynamic-ds.version>4.3.1</dynamic-ds.version>
        <spring-boot-admin.version>3.0.3</spring-boot-admin.version>
        <redisson.version>3.20.1</redisson.version>
        <lock4j.version>2.2.4</lock4j.version>
        <alibaba-ttl.version>2.14.2</alibaba-ttl.version>
        <xxl-job.version>2.4.0</xxl-job.version>
        <mapstruct-plus.version>1.2.1</mapstruct-plus.version>
        <mapstruct-plus.lombok.version>0.2.0</mapstruct-plus.lombok.version>
        <lombok.version>1.18.36</lombok.version>
        <bouncycastle.version>1.72</bouncycastle.version>
        <!-- Apache Commons Compress 版本 -->
        <commons-compress.version>1.26.2</commons-compress.version>
        <!-- 离线IP地址定位库 -->
        <ip2region.version>2.7.0</ip2region.version>
        <!-- OSS 配置 -->
        <aws-java-sdk-s3.version>1.12.400</aws-java-sdk-s3.version>
        <!-- SMS 配置 -->
        <aliyun.sms.version>2.0.23</aliyun.sms.version>
        <tencent.sms.version>3.1.687</tencent.sms.version>

        <!-- 插件版本 -->
        <maven-jar-plugin.version>3.2.2</maven-jar-plugin.version>
        <maven-war-plugin.version>3.2.2</maven-war-plugin.version>
        <maven-compiler-plugin.verison>3.11.0</maven-compiler-plugin.verison>
        <maven-surefire-plugin.version>3.0.0</maven-surefire-plugin.version>
        <flatten-maven-plugin.version>1.3.0</flatten-maven-plugin.version>
    </properties>

    <!-- 依赖声明 -->
    <dependencyManagement>
        <dependencies>

            <!-- Spring AI Alibaba Agent Framework -->
            <dependency>
                <groupId>com.alibaba.cloud.ai</groupId>
                <artifactId>spring-ai-alibaba-bom</artifactId>
                <version>1.1.2.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>1.1.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>io.milvus</groupId>
                <artifactId>milvus-sdk-java</artifactId>
                <version>${milvus.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>dashscope-sdk-java</artifactId>
                <version>${dashscope-sdk-java}</version>
            </dependency>

            <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>${mysql.version}</version>
            </dependency>

            <!-- SpringBoot的依赖配置-->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- hutool 的依赖配置-->
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-bom</artifactId>
                <version>${hutool.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- common 的依赖配置-->
            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-bom</artifactId>
                <version>${revision}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.github.therapi</groupId>
                <artifactId>therapi-runtime-javadoc</artifactId>
                <version>${therapi-javadoc.version}</version>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi</artifactId>
                <version>${poi.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>${poi.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>easyexcel</artifactId>
                <version>${easyexcel.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.poi</groupId>
                        <artifactId>poi-ooxml-schemas</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <!-- velocity代码生成使用模板 -->
            <dependency>
                <groupId>org.apache.velocity</groupId>
                <artifactId>velocity-engine-core</artifactId>
                <version>${velocity.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-jsqlparser</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-annotation</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <!-- dynamic-datasource 多数据源-->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>dynamic-datasource-spring-boot3-starter</artifactId>
                <version>${dynamic-ds.version}</version>
            </dependency>

            <!-- sql性能分析插件 -->
            <dependency>
                <groupId>p6spy</groupId>
                <artifactId>p6spy</artifactId>
                <version>${p6spy.version}</version>
            </dependency>

            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-s3</artifactId>
                <version>${aws-java-sdk-s3.version}</version>
            </dependency>

            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>dysmsapi20170525</artifactId>
                <version>${aliyun.sms.version}</version>
            </dependency>

            <dependency>
                <groupId>com.tencentcloudapi</groupId>
                <artifactId>tencentcloud-sdk-java-sms</artifactId>
                <version>${tencent.sms.version}</version>
            </dependency>

            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>${redisson.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>lock4j-redisson-spring-boot-starter</artifactId>
                <version>${lock4j.version}</version>
            </dependency>

            <!-- xxl-job-core -->
            <!--            <dependency>-->
            <!--                <groupId>com.xuxueli</groupId>-->
            <!--                <artifactId>xxl-job-core</artifactId>-->
            <!--                <version>${xxl-job.version}</version>-->
            <!--            </dependency>-->

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>transmittable-thread-local</artifactId>
                <version>${alibaba-ttl.version}</version>
            </dependency>

            <!-- 加密包引入 -->
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk15to18</artifactId>
                <version>${bouncycastle.version}</version>
            </dependency>

            <!-- Apache Commons Compress -->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-compress</artifactId>
                <version>${commons-compress.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.linpeilie</groupId>
                <artifactId>mapstruct-plus-spring-boot-starter</artifactId>
                <version>${mapstruct-plus.version}</version>
            </dependency>

            <!-- 离线IP地址定位库 ip2region -->
            <dependency>
                <groupId>org.lionsoul</groupId>
                <artifactId>ip2region</artifactId>
                <version>${ip2region.version}</version>
            </dependency>

            <dependency>
                <groupId>org.lixiyun.pojo</groupId>
                <artifactId>pojo</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.pig4cloud.plugin</groupId>
                <artifactId>captcha-spring-boot-starter</artifactId>
                <version>${captcha.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-redis</artifactId>
                <version>${redis.version}</version>
            </dependency>

            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>

            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt</artifactId>
                <version>${jjwt.version}</version>
            </dependency>

            <dependency>
                <groupId>org.mybatis.spring.boot</groupId>
                <artifactId>mybatis-spring-boot-starter-test</artifactId>
                <scope>test</scope>
                <version>${mybatis.version}</version>
            </dependency>

            <dependency>
                <groupId>org.mybatis.spring.boot</groupId>
                <artifactId>mybatis-spring-boot-starter</artifactId>
                <version>${mybatis.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-3-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.pagehelper</groupId>
                <artifactId>pagehelper-spring-boot-starter</artifactId>
                <version>${pagehelper.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-pool2</artifactId>
                <version>${common.pool.version}</version>
            </dependency>

            <dependency>
                <groupId>org.aspectj</groupId>
                <artifactId>aspectjweaver</artifactId>
                <version>${aspectj.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.httpcomponents.client5</groupId>
                <artifactId>httpclient5</artifactId>
                <version>${httpclient.version}</version>
            </dependency>

            <!--            <dependency>-->
            <!--                <groupId>com.github.xiaoymin</groupId>-->
            <!--                <artifactId>knife4j-gateway-spring-boot-starter</artifactId>-->
            <!--                <version>${swagger.gateway}</version>-->
            <!--            </dependency>-->

            <dependency>
                <groupId>org.hibernate.validator</groupId>
                <artifactId>hibernate-validator</artifactId>
                <version>${validator}</version>
            </dependency>

            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
                <version>${knife4j-openapi3-jakarta}</version>
            </dependency>

            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc-ui.version}</version>
            </dependency>

<!--            <dependency>-->
<!--                <groupId>org.springdoc</groupId>-->
<!--                <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>-->
<!--                <version>${springdoc.version}</version>-->
<!--            </dependency>-->

        </dependencies>
    </dependencyManagement>


    <profiles>
        <!-- 以下都是项目环境的定义配置信息，用于在yaml文件中进行引用 -->
        <!-- Maven 在打包时，会把配置值「替换 / 注入」到 yaml 文件里，Spring 启动时读到的已经是替换后的最终值了。 -->
        <!-- Maven 先处理文件 → 生成最终 yaml → Spring 再读取 -->
        <!-- 注意，这种使用方式，需要在 build-resources-resource-filtering 中设置为true，才能使用 -->
        <!-- 注意：以下的日志级别，我设置的是项目全局的日志级别，对于自己开发的项目的日志级别是在yaml的web.logLevel中设置 -->
        <profile>
            <id>local</id>
            <properties>
                <!-- 环境标识，需要与配置文件的名称相对应 -->
                <profiles.active>local</profiles.active>
                <logging.level>debug</logging.level>
            </properties>
        </profile>
        <profile>
            <id>dev</id>
            <properties>
                <!-- 环境标识，需要与配置文件的名称相对应 -->
                <profiles.active>dev</profiles.active>
                <logging.level>info</logging.level>
            </properties>
            <!-- 这里是不指定运行或是打包时，所使用的环境，哪怕是在IDEA中运行默认也是这个 -->
            <activation>
                <!-- 默认环境 -->
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <profiles.active>prod</profiles.active>
                <logging.level>info</logging.level>
            </properties>
<!--            <activation>-->
<!--                &lt;!&ndash; 默认环境 &ndash;&gt;-->
<!--                <activeByDefault>true</activeByDefault>-->
<!--            </activation>-->
        </profile>
        <profile>
            <id>test</id>
            <properties>
                <profiles.active>test</profiles.active>
                <logging.level>debug</logging.level>
            </properties>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <!-- 这三个是指：插件的坐标，是引用其他人的东西，引用谁的，就写谁的名称 -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.verison}</version>
                <configuration>
                    <!-- 指定编写代码时使用的 JDK 语法版本 -->
                    <source>${java.version}</source>
                    <!-- 指定 编译生成的 .class 文件，能在哪个 JDK 版本上运行 -->
                    <target>${java.version}</target>
                    <!-- 指定 Java 代码的文件编码格式 -->
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <!-- 编译时自动生成代码、处理注解 -->
                    <annotationProcessorPaths>
<!--                        <path>-->
<!--                            &lt;!&ndash; 把文档注解中的内容保存到运行时能读取，一般文档注解的内容是运行时消失的 &ndash;&gt;-->
<!--                            &lt;!&ndash; 一般用不上 &ndash;&gt;-->
<!--                            <groupId>com.github.therapi</groupId>-->
<!--                            <artifactId>therapi-runtime-javadoc-scribe</artifactId>-->
<!--                            <version>${therapi-javadoc.version}</version>-->
<!--                        </path>-->
                        <path>
                            <!-- 自动生成 getter/setter/toString 等 -->
                            <!-- AI说这个是用于让编译器自动生成代码，防止出现 编译报错：找不到符号 @Data -->
                            <!-- Maven 3.5+ / IDEA 新版，可以自动识别 Lombok 处理器，不用手动写。 -->
                            <!-- 但只要项目里有其他注解处理器（如 therapi），就必须手动配置！ -->
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <!-- 让自定义配置类在 yml 中有提示，用于先写配置类，再写yaml配置项的 -->
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-configuration-processor</artifactId>
                            <version>${spring-boot.version}</version>
                        </path>
<!--                         如果不使用 MapStruct，以下两个都没用 -->
<!--                        <path>-->
<!--                            &lt;!&ndash; 对象转换工具（DTO ↔ VO ↔ Entity 自动转换） &ndash;&gt;-->
<!--                            <groupId>io.github.linpeilie</groupId>-->
<!--                            <artifactId>mapstruct-plus-processor</artifactId>-->
<!--                            <version>${mapstruct-plus.version}</version>-->
<!--                        </path>-->
<!--                        <path>-->
<!--                            &lt;!&ndash; 让 Lombok 和 MapStruct 兼容不冲突 &ndash;&gt;-->
<!--                            <groupId>org.projectlombok</groupId>-->
<!--                            <artifactId>lombok-mapstruct-binding</artifactId>-->
<!--                            <version>${mapstruct-plus.lombok.version}</version>-->
<!--                        </path>-->
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <!-- 保留方法参数名 -->
                        <!-- 默认情况下，项目运行时，是将参数的名称使用arg0、arg1等名称进行替换的 -->
                        <!-- 例如：Mybatis接口中的(@Param("userId")，因为默认编译后参数名会消失，
                        变成：User selectUser(Long arg0, String arg1);MyBatis 根本不知道 arg0 对应 userId，
                        所以必须手动写 @Param 标记。开启后，编译后真实参数名直接保留 -->
                        <!-- 再例如：Java反射中获取参数名称，默认获取到的也是arg0、arg1 -->
                        <arg>-parameters</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <!-- 单元测试使用 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
                <configuration>
                    <!-- 根据打包环境执行对应的@Tag测试方法，根据环境（dev/test/prod）执行对应标记的测试方法 -->
                    <groups>${profiles.active}</groups>
                    <!-- 排除标签，排除标记为 exclude 的测试 -->
                    <excludedGroups>exclude</excludedGroups>
                    <!-- 跳过测试，直接跳过所有测试 -->
                    <skipTests>true</skipTests>
                </configuration>
            </plugin>
            <!-- 统一版本号管理，CI/CD 自动化发布时统一管理版本号 -->
            <!-- 用于公司微服务 / 多模块项目，要发布到 Maven 私服（Nexus），Jenkins/GitLab 自动化 CI/CD 发布 -->
            <!-- 把 pom.xml 里的所有版本变量（${xxx.version}），在打包时自动替换成真实的数字版本，让项目能正常发布到私服，不报错 -->
            <!-- 可运行的jar包与发布到Maven私服的文件不是同一个东西 -->
            <!-- 可运行的jar包：自己开发的代码、所有的依赖包、被Maven替换完变量的yaml、配置文件 -->
            <!-- 发布到私服的文件：普通轻量 Jar（只含开发的代码，不含任何依赖）、原始 pom.xml（带着 ${xxx.version} 变量，完全没替换）、校验文件 -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>${flatten-maven-plugin.version}</version>
                <configuration>
                    <!-- 在打包时，自动替换 pom 里的变量 -->
                    <updatePomFile>true</updatePomFile>
                    <!-- 只替换CI需要的变量，保留项目必要配置（标准用法） -->
                    <!-- 这个只修改：${revision}主版本号（必须）、${sha1}代码提交哈希（可选）、${changelist}发布标记（可选） -->
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                </configuration>
                <executions>
                    <!-- 把 flatten 插件自动绑定到 Maven 的生命周期里，让插件在打包 / 清理时自动运行，不用手动执行命令 -->
                    <execution>
                        <id>flatten</id>
                        <!-- 绑定Maven生命周期：打包时自动执行替换 -->
                        <phase>process-resources</phase>
                        <goals>
                            <!-- 执行插件的核心功能：扁平化pom、替换变量 -->
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <!-- 绑定Maven生命周期：清理项目时，删掉生成的临时文件 -->
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <!-- 这个配置是告诉 Maven：去哪里找需要处理的配置文件（yaml、properties、xml 等） -->
                <directory>src/main/resources</directory>
                <!-- 只打包 以 application / bootstrap / banner 开头的所有文件，除此之外的所有文件（包括 logback-spring.xml）一律不打包、不加载 -->
<!--                <includes>-->
<!--                    <include>application*</include>-->
<!--                    <include>bootstrap*</include>-->
<!--                    <include>banner*</include>-->
<!--                </includes>-->
                <!-- 启用过滤 即该资源中的变量将会被过滤器中的值替换 -->
                <!-- 这个必须开启，不然yaml文件中的 @xxx@ 就不能替换为Maven中的配置 -->
                <!-- Maven 的 filtering（资源过滤）只能处理纯文本文件 -->
                <!-- 工作流程是：把文件当成 纯文字（字符流） 打开，逐行扫描里面的 @变量@，替换成 Maven 配置的值，重新保存文件 -->
                <filtering>true</filtering>
                <!-- 排除所有二进制文件，避免解析报错 -->
                <excludes>
                    <exclude>**/*.xdb</exclude>
                    <exclude>**/*.jpg</exclude>
                    <exclude>**/*.jpeg</exclude>
                    <exclude>**/*.png</exclude>
                    <exclude>**/*.gif</exclude>
                    <exclude>**/*.bmp</exclude>
                    <exclude>**/*.ico</exclude>
                    <exclude>**/*.jar</exclude>
                    <exclude>**/*.zip</exclude>
                    <exclude>**/*.gz</exclude>
                </excludes>
            </resource>
            <!-- 二进制文件：关闭过滤，原样复制（ip2region.xdb/图片等） -->
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <!-- 只包含二进制文件 -->
                <includes>
                    <include>**/*.xdb</include>
                    <include>**/*.jpg</include>
                    <include>**/*.jpeg</include>
                    <include>**/*.png</include>
                    <include>**/*.gif</include>
                    <include>**/*.bmp</include>
                    <include>**/*.ico</include>
                    <include>**/*.jar</include>
                    <include>**/*.zip</include>
                    <include>**/*.gz</include>
                </includes>
            </resource>
        </resources>
    </build>

</project>