<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.lixiyun</groupId>
    <artifactId>common-bom</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <description>
        common-bom common依赖项
    </description>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <revision>1.0.0</revision>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-vector</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-sql</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-mail</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-web</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-verification-code</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-validation</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-authentication</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-aop</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-core</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-redis</artifactId>
                <version>${revision}</version>
            </dependency>

            <!-- OSS -->
            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-oss</artifactId>
                <version>${revision}</version>
            </dependency>

            <!-- 短信模块 -->
            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-sms</artifactId>
                <version>${revision}</version>
            </dependency>

            <!-- 翻译模块 -->
            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-translation</artifactId>
                <version>${revision}</version>
            </dependency>

            <!-- 脱敏模块 -->
            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-sensitive</artifactId>
                <version>${revision}</version>
            </dependency>

            <!-- 序列化模块 -->
            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-json</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-websocket</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-agent</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>org.lixiyun</groupId>
                <artifactId>common-file</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>

    </dependencyManagement>


</project>